export const ACTION_NOTIFICATION = 'ACTION_NOTIFICATION'
export const ACTION_NOTIFICATION_SUCSESS = 'ACTION_NOTIFICATION_SUCSESS'
export const ACTION_NOTIFICATION_FAILURE = 'ACTION_NOTIFICATION_FAILURE'